src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoQMain.java
warn instead of disabling the module entirely, change the formatting if you want#
#160
=> warn instead of disabling autoqmain when not on 2b2t.org

src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoQMain.java
=> Revert "warn instead of disabling autoqmain when not on 2b2t.org"

src/main/java/me/zeroeightsix/kami/module/modules/sdashb/experimental/NoSoundLag.java, src/main/java/me/zeroeightsix/kami/module/modules/sdashb/misc/AutoWither.java
Added an option for nametags to AutoWither #156  (may have some issues) and added NoSoundLag #186 .
=> Add Nametags to AutoWither and add NoSoundLag

docs/TROUBLESHOOTING.md
Got help solving this through discord, and thought it should go in here.
=> Crash when compiling with spongepowered error

src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiScreen.java
`package me.zeroeightsix.kami.module.modules.misc;
import me.zeroeightsix.kami.module.Module;
@Module.Info(name = "CleanGUI", category = Module.Category.MISC)
public class CleanGUI extends Module {
}`
=> removes default gui background

src/main/java/me/zeroeightsix/kami/module/modules/bewwawho/capes/Capes.java
=> fix credit !

src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiNewChat.java
This adds a quick fix to the mixin for chat rendering and adds that sweet and clean look Bella was going for.
=> Made the cleangui module toggle a non-shadowed string. Close #339

src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiNewChat.java
=> Revert "Made the cleangui module toggle a non-shadowed string. Close #339"

src/main/java/me/zeroeightsix/kami/module/modules/zeroeightysix/render/ChunkFinder.java
you were not saving new chunks anymore after closing the file once
=> fix bug Chunkfinder bug

src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.java
=> Don't run prefixchat when sneaking

src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java, src/main/java/me/zeroeightsix/kami/module/modules/combat/StrengthDetect.java
Shows if someone is under the influence of Strength like this: https://imgur.com/a/zVOcxx1 .
Use it if you want idrc. Weakness effect can be added aswell
=> Textradar StrengthDetect

src/main/java/me/zeroeightsix/kami/setting/converter/EnumConverter.java, src/main/java/me/zeroeightsix/kami/setting/impl/EnumSetting.java
Fixed the enum setting issue and now goes back to the default value
Closes #213
=> [Fix] Enum Setting

src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityRenderer.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinFrustum.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinRenderGlobal.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinVisGraph.java, src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.java, src/main/resources/kami_at.cfg, src/main/resources/mixins.kami.json
See https://github.com/zeroeightysix/KAMI/pull/178
Discussion in #449
=>  Freecam fix render range #449 

src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.java
=> probably fixes the crash

src/main/java/me/zeroeightsix/kami/command/commands/FriendCommand.java, src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.java, src/main/java/me/zeroeightsix/kami/module/modules/misc/MidClickFriends.java
This Closes #302 at last kek...
=> [Added] MidClickFriends  Closes #302

src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoFish.java
=> Make autofish faster

src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java
uwu big brain moment and thats on keeping it a 1liner
Closes #532
=> fix not searching if items were in offhand <3

src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.java
=> Add hunger options to autoeat and don't eat bad food 

src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.java
=> Add a ton of options to AntiSpam and make detection better

src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.java
Fixed the commit signature issue
=> Autoeat no longer eats poisonous potatoes

src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatTimestamp.java, src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java, src/main/java/me/zeroeightsix/kami/setting/converter/EnumConverter.java, src/main/java/me/zeroeightsix/kami/util/ColourUtils.java, src/main/java/me/zeroeightsix/kami/util/TimeUtil.java
... in order to finish up ColourTextFormatting for ActiveModules
=> Switch colors to use TextFormatting 

src/main/java/me/zeroeightsix/kami/command/Command.java, src/main/java/me/zeroeightsix/kami/command/CommandManager.java, src/main/java/me/zeroeightsix/kami/command/commands/ToggleCommand.java, src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiChat.java
Reimplements #373, closes #358 
Added aliases and aliases auto completions 😄
=> added aliases to commands

src/main/java/me/zeroeightsix/kami/DiscordPresence.java, src/main/java/me/zeroeightsix/kami/module/modules/misc/DiscordSettings.java
Fixed the RPC disconnect issue.
Closes #393
=> Discord RPC Disconnect

src/main/java/me/zeroeightsix/kami/command/Command.java, src/main/java/me/zeroeightsix/kami/command/commands/ActiveModulesCommand.java, src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java, src/main/java/me/zeroeightsix/kami/module/modules/gui/ActiveModules.java
=> Add custom colors to active modules categories 

src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.java, src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoTool.java
=> Rewrite aura and autotool logic 

scripts/ver.sh, src/main/java/me/zeroeightsix/kami/KamiMod.java, src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiUpdateNotification.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiMainMenu.java, src/main/java/me/zeroeightsix/kami/util/WebUtils.java, src/main/resources/mixins.kami.json
Looks good to me 👌
Closes #587
=> Merge the update checker

src/main/java/me/zeroeightsix/kami/mixin/client/MixinTileEntityBeacon.java, src/main/java/me/zeroeightsix/kami/module/modules/render/NoRender.java, src/main/resources/mixins.kami.json
=> Add Beacon Beams to NoRender

src/main/java/me/zeroeightsix/kami/util/LogUtil.java
LogUtil can now log chunk coordinates or normal coordinates, instead of normal ony.
LogUtil also has a function to get the current coordinates of the player and return them in an array, can also return chunk coordinates.
=> Improvements to LogUtil

src/main/java/me/zeroeightsix/kami/module/modules/render/Search.java, src/main/java/me/zeroeightsix/kami/setting/builder/numerical/NumericalSettingBuilder.java
- Use Executors to handle Threads efficiently
- Sliced Search by chunks
- Added slider for Update Interval
- Reacts to Chunk events
=> Improvements to Search Module

src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
- logs shulkers and chests
- can set minimum amount until chunk is logged
ez stash
Closes #430
=> Add a Stashfinder module

src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.java
Tower option which works fine on 2b2t. Also fixes an apparent bug where the module would not switch to building blocks.
Closes #252
=> Scaffold tower

src/main/java/me/zeroeightsix/kami/module/modules/misc/MountBypass.java
This allows you to mount donkeys on servers that may disallow it
Tests Performed: it builds.
=> Add MountBypass

src/main/java/me/zeroeightsix/kami/gui/kami/DisplayGuiScreen.java, src/main/java/me/zeroeightsix/kami/module/modules/movement/InventoryMove.kt
Don't pause GUI in singleplayer
=> InventoryMove: Fix AAC kick from pitch overflows

src/main/java/me/zeroeightsix/kami/module/modules/movement/AutoRemount.java
features:
* doesn't mount children
* boats
* horses
* skeletonhorses
* donkeys
* pigs (saddle check)
* llamas
Next up of adding is a delay, but that will be for another time.
Closes #778
=> AutoRemount now works with other mountable entities

src/main/java/me/zeroeightsix/kami/module/modules/render/Search.java
---
name: Speed up search
about: Change mc.theWorld to chunk
---
This pr improves performance when using the search module.
CPU usage is significantly reduced.
Discussed on discord.
=> Change from mc.theWorld to chunk

src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java, src/main/java/me/zeroeightsix/kami/module/modules/chat/FriendHighlight.kt
This pull request should fix two problems with the friends system.
- It gives a minimum width to the Friends list in the GUI regardless of whether it is minimized.
- It fixes an issue where only the name of the last friend in a player's friends list will be highlighted, not any other name.
=> Fixing problems with friends.

src/main/java/me/zeroeightsix/kami/command/commands/CoordsCommand.java, src/main/java/me/zeroeightsix/kami/util/CoordinateInfo.java
This pr does fixes some stuff and adds IDs to coordinates.
This pr makes the `;pos stashes` command work again and adds IDs to saved coordinates for future QoL updates.
Preparation for baritone support.
=> Fixed stash list command regex, added IDs to CoordinateInfo

src/main/java/me/zeroeightsix/kami/process/TemporaryPauseProcess.java
A clear and concise description of what the pull is for.
A clear description of why this should be merged
=> Update TemporaryPauseProcess.java (#864) (leijurv)

src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.kt
Fixes bug where autoeat module will eat pufferfish.
The player doesn't eat pufferfish ^w^.
=> Fixed autoeat eating pufferfish, issue #875

src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
Fixed Elytraflight Look Boost working when not moving
It will not boost you when ur not moving and just looking up to see smth idk
Nothing
=> Fixed Look Boost working when not moving

src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
Closes #881 
You can jump freely without turning off elytraflight when elytra is not equipped.
=> Added elytra check, issue #881

src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.java, src/main/java/me/zeroeightsix/kami/module/modules/misc/DiscordRPC.kt
As what the title says
Closing issue #1008
=> Add hunger, speed, helditem, fps, tps options to DiscordRPC

src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.kt
Changed hypixel mode to send a "hypixel censor message"
The Hypixel mode on AutoEZ is lackluster. This changes it to send a Hypixel filter message.
The old Hypixel autoez was lackluster, this fixes that.
Kotlin is based
=> Added actual hypixel messages to AutoEZ

src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.kt
bugfix
i dont want to see $name
my kotlin skills are not based
=> Fixed Error

src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java, src/main/java/me/zeroeightsix/kami/module/modules/chat/FancyChat.kt
Fixed the InventoryViewer where it would stay massive and have to way to minimize.
Added bluetext to FancyChat for the servers that support it.
Makes the GUI less cluttered.
More functionality I guess...?
Nothin
=> Fixed inventory viewer height & added blue to fancychat

src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt, src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt, src/main/java/me/zeroeightsix/kami/util/CenterPlayer.kt
1, Better auto center for surround
2, Added page switching to organize settings.
3, Added acceleration. (by Dominika)
4, Made acceleration non linear.
4, Added boost speed c for bypassing boost speed limit on some server.
5, Cleaned up settings.
6, Hopefully fixed rubber banding issue caused by canceling CPacketPlayer.
7, Added auto landing. (issue #900)
~~8, Don't run takeoff if player is in water or lava.~~
9, Takeoff holds player in the air if server is lagging and distance is enough for taking fall damage.
10, Takeoff slows down falling speed to increase success rate
11, Takeoff will reset player back on ground if too close to ground.
12, Removes leg swings while flying.
13, Runs takeoff in liquid, but not slowing down fall speed
14, Reset flying states when …
=> Improved ElytraFlight and moved Surround calcs to a util

src/main/java/me/zeroeightsix/kami/DiscordPresence.java, src/main/java/me/zeroeightsix/kami/module/modules/misc/DiscordRPC.kt
No separator when one field is empty in DiscordRPC module
Resolved Issue #1033
N/A
=> No separator when one field is empty in DiscordRPC module

src/main/java/me/zeroeightsix/kami/module/modules/chat/CustomChat.kt
it used to be blue dot bella dot what tf
ｋａｍｉｂｌｕｅ．ｏｒｇ
new website
kami blue was the first client to have bread
=> Updated website link

src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoExcuse.kt
Added more excuses
Added more excuses
Added more excuses
=> Added more excuses

src/main/java/me/zeroeightsix/kami/module/modules/movement/Step.kt, src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt, src/main/java/me/zeroeightsix/kami/util/PacketHelper.java
=> Added Step

src/main/java/me/zeroeightsix/kami/module/modules/movement/Strafe.kt, src/main/java/me/zeroeightsix/kami/util/MovementUtils.kt, src/main/java/me/zeroeightsix/kami/util/StrafeUtils.kt
Added fast strafe which bypasses ncp
#633 #180 #852 👀 
Code is kinda bad but it works
=> Added Strafe

src/main/java/me/zeroeightsix/kami/mixin/client/MixinFontRenderer.java
1. Fixed MixinFontRenderer compatibility issues with other mods #1135
2. Fixed MixinFontRenderer build errors
Thanks dewy ♿
=> Fixed MixinFontRenderer incompatibility and build errors

src/main/java/me/zeroeightsix/kami/module/modules/player/InventoryManager.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/HoleESP.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/SelectionHighlight.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/WaypointRender.kt, src/main/java/me/zeroeightsix/kami/util/BetterArrayList.kt, src/main/java/me/zeroeightsix/kami/util/ESPRenderer.kt, src/main/java/me/zeroeightsix/kami/util/KamiTessellator.kt
1. Fixed a bug causing Search and AutoEject list not saving correctly
2. Added parameter to drawOutline to draw outline only for specified side 
3. Added option to SelectionHighlight to only draw square for hit side
4. Fixed HoleESP down mode not working #1126 
5. Renamed HoleESP down mode to flat mode
6. Added block floor mode to HoleESP
=> Render bug fixes

src/main/java/me/zeroeightsix/kami/module/modules/client/InventoryViewer.java
Fixed PlayerModel enchant glint issue #995, might need more tests to make sure not breaking any other modules
=> Fixed PlayerModel enchant glint issue #995

src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.java
Adds square walking using baritone with configurable radius in order to bypass 2b2t's antiAFK plugin.
=> Updated AntiAFK to work on 2b2t

src/main/java/me/zeroeightsix/kami/mixin/client/MixinFontRenderer.java
1. Rewrote MixinFontRenderer
2. Fixed KamiMoji incompatibility with Smooth Font mod
1. Much cleaner codes
2. Emoji will be scaled correctly with Smooth Font mod enabled
=> Fixed KamiMoji incompatibility with SmoothFont

src/main/java/me/zeroeightsix/kami/module/modules/render/BreakingESP.kt
Removes block position in the list if it is air block
Fixed BreakingESP shows ESP after block has been broken #1177
=> Fixed BreakingESP showing after block was broken

src/main/java/me/zeroeightsix/kami/module/modules/render/Breadcrumbs.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/EyeFinder.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/Nametags.java, src/main/java/me/zeroeightsix/kami/module/modules/render/SelectionHighlight.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/WaypointRender.kt, src/main/java/me/zeroeightsix/kami/util/ESPRenderer.kt, src/main/java/me/zeroeightsix/kami/util/KamiTessellator.kt
=> Fixed render modules jitters in paused single player world

src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityRenderer.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinModelPlayer.java, src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt, src/main/resources/mixins.kami.json
1. Added swing animation to ElytraFlight
2. Removed view changing while going down with ElytraFlight
3. Fixed random error in MixinEntityRenderer
1. Big Future meme
2. Less annoying while going down in third person view
3. No more red code in IDE
=> Added animations to ElytraFlight

src/main/java/me/zeroeightsix/kami/module/modules/combat/MidClickPearl.kt
Added MidClickPearl issue #1119
=> Added MidClickPearl

src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraReplace.kt
This overhauls the current ElytraReplace code and makes it somewhat readable and usable.
I made the code a bit more modular, made some boolean logic easier to follow, and maybe fixed a bug? 
I am a bit unfamiliar with kotlin, so if there are any convention / best practices violations please don't hesitate to let me know. Also if there is a style guide that I missed I'll be happy to modify my code accordingly. 
I have already tested it out in a singleplayer world, and it should work in a multiplayer world as I borrowed the swapping code from auto-armor
=> Revamped ElytraReplace

src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiStealButton.kt, src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiContainer.java, src/main/java/me/zeroeightsix/kami/module/modules/player/ChestStealer.kt, src/main/java/me/zeroeightsix/kami/module/modules/player/InventoryManager.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt, src/main/java/me/zeroeightsix/kami/util/InventoryUtils.kt, src/main/resources/mixins.kami.json
1. Added ChestStealer
2. Fixed AutoEject and Search list not initialized error
1. #498 
2. Bug fix
=> Added ChestStealer and some bug fix

src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/RadarUI.java
Fixed white screen caused by Radar, needs some testings
=> Fixed white screen caused by Radar

src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java, src/main/java/me/zeroeightsix/kami/module/modules/render/BreakingESP.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/EyeFinder.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/HoleESP.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/SelectionHighlight.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/StorageESP.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/Trajectories.java, src/main/java/me/zeroeightsix/kami/module/modules/render/WaypointRender.kt, src/main/java/me/zeroeightsix/kami/util/ESPRenderer.kt, src/main/java/me/zeroeightsix/kami/util/KamiTessellator.kt
1. Fixed wrong chunks being added to loaded chunks list
2. Multi-threading performance optimization
3. Removed square vec fool proof comparison
4. Optimized ESPRenderer code
5. Removed unused partial ticks parameters from ESP renderer constructor
Better performance and more readable codes
=> Improved Search Rendering and Calculation

src/main/java/me/zeroeightsix/kami/gui/font/CFontRenderer.java, src/main/java/me/zeroeightsix/kami/gui/kami/RootFontRenderer.java, src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiEnumButtonUI.java, src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootButtonUI.java, src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootCheckButtonUI.java, src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootLabelUI.java, src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootSliderUI.java, src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/TabGuiUI.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiInventory.java, src/main/java/me/zeroeightsix/kami/module/modules/render/PlayerModel.kt
1. All blend state issues should now be fixed
2. Force drawEntityOnScreen to use interpolation for smoother animation
1. No more white chat
2. Smoother PlayerModel
=> Radar render fix and smoother PlayerModel

src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.kt
Cleaned up and fixed some parts of AntiSpam.
Resolves bug where duplicates were not being properly marked.
Removed a few comments which I felt were unnecessary.
Adjusted wording for the ownFilter comment to make it a bit clearer.
I was considering expanding on the AntiSpam module and adding something that would sanitize chat suffixes, but I felt that it would be better for another module entirely devoted to sanitizing chat instead of just filtering.
=> Fixed Anti-Duplicate bug + Cleanup

src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoFish.kt, src/main/java/me/zeroeightsix/kami/util/BlockUtils.kt
1. Added liquid block check utils to BlockUtils
2. Added Bounce, Any Splash, All mode to auto fish
1. Used by AutoFish
2.  Bypass on some servers like 2b2t, closes #940 
Test video is in #announcement channel in KB Discord server
=> Updated AutoFish to work on all servers, and made AutoRecast better

src/main/java/me/zeroeightsix/kami/module/modules/chat/Spammer.kt
Fixed Spammer random mode attempting to get a different message while there is only 1 message in the message list.
Closes #1185
=> Fixed Spammer random mode does work with 1 line

src/main/java/me/zeroeightsix/kami/util/MessageSendHelper.java
Just a fool foolproof avoiding sending empty message to the server
Closes #1194
=> Fixed getting kicked while attempting to send empty message

src/main/java/me/zeroeightsix/kami/module/modules/player/Fastuse.kt
1. Make blocks optional in FastUse and not included in the All option
2. Added bow charge variation option
1. Closes #1166 
2. Bypass some weird server plugins
=> Enhancement for FastUse

src/main/java/me/zeroeightsix/kami/event/events/OnUpdateWalkingPlayerEvent.kt, src/main/java/me/zeroeightsix/kami/manager/mangers/PlayerPacketManager.kt, src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java, src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt, src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt, src/main/java/me/zeroeightsix/kami/util/math/Vec2f.kt
1. Added mixins and event for onUpdateWalkingPlayer in EntityPlayerSP
2. Added PlayerPacketManger
3. Added Vec2f
4. Made Aura and ElytraFlight use PlayerPacketManger for packet spoofing
1. Closes #779 
2. Easier way to modify CPacketPlayer being sent by vanilla mc code. Avoid conflicts caused by multiple module making modification at the same time.
3. Better way to store rotations
4. Cleaner codes, no conflict
Thank you ionar2 for the issue
Testing videos:
https://discordapp.com/channels/573954110454366214/634010567107149824/748601664575111228
https://discordapp.com/channels/573954110454366214/634010567107149824/748659038597677217
https://discordapp.com/channels/573954110454366214/634010567107149824/74866027 …
=> Added PlayerPacketManager

src/main/java/me/zeroeightsix/kami/manager/mangers/PlayerPacketManager.kt, src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java
Should fixed incompatibility with other clients.
Testing needed.
=> Rewrote PlayerPacketManger mixins

src/main/java/me/zeroeightsix/kami/gui/kami/component/SettingsPanel.java, src/main/java/me/zeroeightsix/kami/gui/rgui/component/use/Slider.java, src/main/java/me/zeroeightsix/kami/module/modules/misc/PingSpoof.kt, src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt, src/main/java/me/zeroeightsix/kami/module/modules/player/Timer.kt, src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt, src/main/java/me/zeroeightsix/kami/setting/builder/numerical/DoubleSettingBuilder.java, src/main/java/me/zeroeightsix/kami/setting/builder/numerical/FloatSettingBuilder.java, src/main/java/me/zeroeightsix/kami/setting/builder/numerical/IntegerSettingBuilder.java, src/main/java/me/zeroeightsix/kami/setting/builder/numerical/NumericalSettingBuilder.java, src/main/java/me/zeroeightsix/kami/setting/impl/numerical/DoubleSetting.java, src/main/java/me/zeroeightsix/kami/setting/impl/numerical/FloatSetting.java, src/main/java/me/zeroeightsix/kami/setting/impl/numerical/IntegerSetting.java, src/main/java/me/zeroeightsix/kami/setting/impl/numerical/NumberSetting.java
Added `withStep()` too number setting builders.
I can finally slide the settings freely and precisely ♿ 
https://cdn.discordapp.com/attachments/634010567107149824/758051877924372590/2020-09-22_15-45-43.mp4
=> Slider Step Fix

README.md
Added star chart in readme
more content
merge this fast
=> Added star chart.

detekt.yml, src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntity.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityRenderer.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinFrustum.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinMovementInputFromOptions.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinRenderPlayer.java, src/main/java/me/zeroeightsix/kami/mixin/client/MixinVisGraph.java, src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoFeetPlace.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.java, src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt, src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoTunnel.kt, src/main/java/me/zeroeightsix/kami/module/modules/movement/AutoWalk.kt, src/main/java/me/zeroeightsix/kami/module/modules/movement/Jesus.kt, src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.kt, src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.kt, src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt, src/main/java/me/zeroeightsix/kami/util/math/MathUtils.kt
1. Rewrote Freecam with fully compatibility with Baritone
2. Fixed all current bugs with Freecam
1. closes #530
2. closes #1160, (#1174 should be closed in the combat branch)
See announcement channel in Kami Blue discord for test video
=> Rewrote Freecam

src/main/java/me/zeroeightsix/kami/module/modules/combat/AntiBot.kt
this is a typo, right?
A clear and concise description of what the pull is for.
A clear description of why this should be merged
Add any other context about the pull here. 
i
i think this counts as a contribution?
=> typo in antibot

src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
I hope this works
Hey, it's me again. Again, I am just adding something simple.
=> [feature] Added hoppers to Stashfinder

src/main/java/me/zeroeightsix/kami/manager/mangers/CombatManager.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/CombatSetting.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalBasePlace.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalESP.kt, src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt, src/main/java/me/zeroeightsix/kami/util/MotionTracker.kt, src/main/java/me/zeroeightsix/kami/util/Quad.kt, src/main/java/me/zeroeightsix/kami/util/combat/CrystalUtils.kt, src/main/java/me/zeroeightsix/kami/util/math/RotationUtils.kt
1. Fixed some bugs
2. Multithreaded damage calculations
3. Use player eye position instead of feet position for distance check in Crystal Aura
4. Make Crystal Aura wall distance check more accurate
5. Added Crystal Base Place
1. Bug fixes lol
2. Better performance
3. More accurate distance check
4. More accurate distance check
5. Helps with placing crystal
=> [feature] CrystalBasePlace and CrystalAura enhancements 

src/main/java/me/zeroeightsix/kami/module/modules/render/NoRender.kt
https://github.com/kami-blue/client/issues/1480
=> Added particles to norender

src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoExcuse.kt
Improvement to AutoExcuse module, making it read from a custom file.
free pr merge it or leave it
closes #1032
=> [feature] Custom excuse options for AutoExcuse

src/main/java/me/zeroeightsix/kami/manager/mangers/CombatManager.kt, src/main/java/me/zeroeightsix/kami/manager/mangers/PlayerInventoryManager.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/AimBot.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoArmor.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/BedAura.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalBasePlace.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/HoleMiner.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt, src/main/java/me/zeroeightsix/kami/util/InventoryUtils.kt
1. Added Player Inventory Manager.
2. Fixed Auto Amor bug.
3. Added annotation to indicate modules that should be in CombatManager.
1. Queueing inventory clicking and execute them one by one.
2. Closes #1477 
3. Fixed compatibility with AutoArmor priority
=> [feature] Player Inventory Manager

src/main/java/me/zeroeightsix/kami/mixin/client/MixinTileEntitySignRenderer.java, src/main/java/me/zeroeightsix/kami/module/modules/render/NoRender.kt, src/main/resources/mixins.kami.json
i added a norender option for signtext. it still shows text when you place a sign and edit the text in your guiscreen. 
should i make an option to not render signs at all ? 
issue #1303
=> [feature] Added Norender option for signtext

src/main/java/me/zeroeightsix/kami/mixin/client/MixinWorld.java, src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiWeather.kt
i hope this fixes the flickering in antiweather
i made antiweather use mixin
=> [fix] Bug with AntiWeather

src/main/java/me/zeroeightsix/kami/module/modules/render/VoidESP.kt
Adds a VoidESP module. Closes #1344.
New feature for the mod, VoidESP.
No.
=> [feature] Created VoidESP

src/main/java/me/zeroeightsix/kami/module/modules/combat/HoleESP.kt
Adds an option to HoleESP to hide the hole the player is standing in.
Just a cosmetic feature, and there is no need to render a hole if the player is inside it.
Some other mods have it.
=> [feature] Added HideOwn option to HoleESP

src/main/resources/mcmod.info
Makes kami look nice in the MultiMC mod list, and probably other places too.
Just makes things a tiny bit nicer
Mfw kami fat
=> Removed newline in mcmod.info

src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.kt
An updated version of them.
This is an updated version of hypixel EZ
It's nice to be updated and have more funny sentences. 
Got the info from a form post.
=> Added some more hypixel ez

src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoExcuse.kt
I didn't do anything useful yet lol, but I'm learning Kotlin rn so I hope I can actually code later.
Just added some more auto excuses and clients.
Nice to have some more sentences cus rn there's only like 7, I know there an option to add more but more ppl don't use it.
Nothing.
=> [enhancement] Added more excuses to AutoExcuse

src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoExcuse.kt
Removed "Rusherhack" from the clients variable
"Rusherhack" should not be here.
=> Improve AutoExcuse

src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.kt, src/main/java/me/zeroeightsix/kami/util/InfoCalculator.kt, src/main/resources/kami_at.cfg
I removed Chunksize because i think it will fix the bug described in issue #1434
=> [fix] Removed ChunkSize to fix weird invisible entities bug

.gitmodules, build.gradle, src/main/java/me/zeroeightsix/kami/manager/Manager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/CombatManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/FileInstanceManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/FriendManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/KamiMojiManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/MacroManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/MessageManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/PlayerInventoryManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/PlayerPacketManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/WaypointManager.kt, src/main/java/me/zeroeightsix/kami/module/modules/client/Capes.kt
1. Organized submodules/project directory
2. Added common utils
3. Rewrote Capes to use the new cape-api
=> [refactor] Packages and managers 

src/main/java/me/zeroeightsix/kami/module/modules/chat/FriendHighlight.kt
I have developed an algorithm that plays an Auditory ping when FriendHighlight finds a friend ( issue #1558)
=> Added sound to FriendHighlight.

build.gradle, src/main/java/me/zeroeightsix/kami/KamiMod.java, src/main/java/me/zeroeightsix/kami/command/CommandManager.kt, src/main/java/me/zeroeightsix/kami/manager/ManagerLoader.kt, src/main/java/me/zeroeightsix/kami/module/ModuleManager.kt
Signed-off-by: Dominika <sokolov.dominika@gmail.com>**Describe the pull**
=> [revert] Use old reflection utils

src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.kt
Closes #1633 + small cleanup regarding the (incredibly funny) entity ID
=> Fix freecam chunk rendering

src/main/java/me/zeroeightsix/kami/module/modules/render/BossStack.kt
Added a censor option for BossStack to solve #1638 
This is the version has creates the bossbars form mc.ingameGUI.bossOverlay.mapBossInfos.
As discussed on #1638 a version that uses the loaded entities would be possible. 
That version could differentiates between bosstypes 
but it would discards any custom bossbars that are not connected to an entity.
I'd suggest to just test this version and let me know if you instead want the other one.
Side notes:
In getMatchBoss() we were matching a percent value ∈ [0,1] to a value ∈ [0,100].
To my knowledge it is not possible to name Ender dragons or have more than one ender dragon alive in survival vanilla.
=> [feature] Censor option for BossStack

src/main/java/me/zeroeightsix/kami/mixin/client/accessor/AccessorMinecraft.java, src/main/java/me/zeroeightsix/kami/mixin/extension/Misc.kt, src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoMine.kt
Adds a manual mode to automine. 
This means that it just mines the block one is facing at, not using baritone.
=> [feature] Add manual mode to automine.

.github/workflows/gradle_build.yml, .travis.yml
Travis ci doesn't t like open source anymore so move on to Github Actions
=> [feature] Added Github Actions

src/main/java/me/zeroeightsix/kami/command/ExecuteEvents.kt, src/main/java/me/zeroeightsix/kami/manager/managers/PlayerPacketManager.kt, src/main/java/me/zeroeightsix/kami/mixin/client/entity/MixinEntity.java, src/main/java/me/zeroeightsix/kami/module/Module.kt, src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.kt, src/main/java/me/zeroeightsix/kami/util/BlockUtils.kt, src/main/java/me/zeroeightsix/kami/util/math/VectorUtils.kt
Rewrote scaffold to make it actually works.
closes #732
closes #924
closes #1244
Tested on:
crystalpvp.us - Horizontal & non continuous tower
2b2tpvp.net - Horizontal & tower
crystalpvp.cc - Horizontal & vertical with tower off (might be ping issue)
oldfag.org - Horizontal & vertical with tower off
=> [enhancement] Scaffold

src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatEncryption.kt
Add a new type of cipher (Vignere) and improve upon the chat encryption module.
Closes #874, closes #723
=> [enhancement] Improve ChatEncryption module

src/main/java/me/zeroeightsix/kami/module/modules/movement/Jesus.kt
Adds a dolphin mode to Jesus
It can bypass some anticheats.
closes #1178
Hopefully the formatting is better, do you know if there is a document that lays out the general standards for kotlin formatting?
=> [enhancement] Add dolphin mode to Jesus (#1178)

src/main/java/me/zeroeightsix/kami/mixin/client/accessor/network/AccessorCPacketUseEntity.java, src/main/java/me/zeroeightsix/kami/mixin/extension/Network.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.kt, src/main/java/me/zeroeightsix/kami/util/combat/CombatUtils.kt, src/main/resources/mixins.kami.json
Added packet explode
Added predict explode
Fixed damage calculation thread safety
Cleaned up settings
=> [enhancement] Added PacketExplode and PredictExplode to CrystalAura

src/main/java/me/zeroeightsix/kami/gui/hudgui/HudElement.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/KamiHudGui.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/LabelHud.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/BaritoneProcess.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/ModuleList.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/WaterMark.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/Armor.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/CombatItemCount.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/misc/Time.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/player/InventoryViewer.kt, src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/player/PlayerModel.kt
Added option to scale each hud element seperately
=> [enhancement] Hud element scaling

.github/FUNDING.yml
I saw that you are changing these links and found one without changing
=> [fix] Don't use hardcoded Paypal URL

src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiStealButton.kt, src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiStoreButton.kt, src/main/java/me/zeroeightsix/kami/mixin/client/gui/MixinGuiContainer.java, src/main/java/me/zeroeightsix/kami/module/modules/player/ChestStealer.kt
Adds a store option to chest stealer.
It is sometimes useful.
Closes #498.
=> [enhancement] Add store option to ChestStealer.

src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt
Add a option to set the message for visual range.
closes #1320
=> [enhancement] Add custom message to visual range.

src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoMend.kt, src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt, src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
implemented the feature requested in #1846
=> [feature] Nearby player check for AutoMend

src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.kt
Adds an option to disable allow break when antiAFK is enabled. 
Closes #1865
=> [enhancement] add allowBreak setting to antiAFK.

src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.kt, src/main/java/me/zeroeightsix/kami/event/KamiEventBus.kt, src/main/java/me/zeroeightsix/kami/event/KamiEvents.kt, src/main/java/me/zeroeightsix/kami/event/events/PlayerTravelEvent.kt, src/main/java/me/zeroeightsix/kami/event/events/RenderEntityEvent.kt, src/main/java/me/zeroeightsix/kami/event/events/RenderOverlayEvent.kt, src/main/java/me/zeroeightsix/kami/event/events/RenderWorldEvent.kt, src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinEntityRenderer.java, src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinRenderManager.java, src/main/java/me/zeroeightsix/kami/util/threads/ThreadSafety.kt
Helpful for tracking performance stuff.
=> [enhancement] Added profiler support for individual listener

build.gradle, src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt
SpongePowered has updated their Maven repo URL and this should fix it
=> [fix] Update SpongePowered Maven URL

src/main/java/me/zeroeightsix/kami/manager/managers/FriendManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/MacroManager.kt, src/main/java/me/zeroeightsix/kami/manager/managers/WaypointManager.kt, src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatFilter.kt, src/main/java/me/zeroeightsix/kami/module/modules/chat/Spammer.kt, src/main/java/me/zeroeightsix/kami/util/ConfigUtils.kt
Closes #310
Signed-off-by: lv <~@l1v.in>
=> [fix] Move all configs to `kamiblue` folder

build.gradle, src/main/java/me/zeroeightsix/kami/KamiMod.java, src/main/java/me/zeroeightsix/kami/command/commands/DiscordNotifsCommand.kt, src/main/java/me/zeroeightsix/kami/module/modules/chat/DiscordNotifs.kt
=> [cleanup] Switch to OkHttp from dumb http libraries

build.gradle, src/main/java/me/zeroeightsix/kami/KamiMod.java, src/main/java/me/zeroeightsix/kami/module/modules/chat/DiscordNotifs.kt
Removed useless extra 1mb from the jar. ConnectionUtils rewrite will be later since it is also being used by the cape api.
=> [cleanup] Removed bloat http request lib

src/main/kotlin/org/kamiblue/client/command/CommandManager.kt, src/main/kotlin/org/kamiblue/client/module/modules/client/CustomFont.kt, src/main/kotlin/org/kamiblue/client/module/modules/misc/FakePlayer.kt, src/main/kotlin/org/kamiblue/client/module/modules/misc/LogoutLogger.kt, src/main/kotlin/org/kamiblue/client/module/modules/misc/StashLogger.kt, src/main/kotlin/org/kamiblue/client/module/modules/player/Freecam.kt, src/main/kotlin/org/kamiblue/client/module/modules/render/NewChunks.kt, src/main/kotlin/org/kamiblue/client/util/items/Operation.kt, src/main/kotlin/org/kamiblue/client/util/threads/MainThreadExecutor.kt, src/main/kotlin/org/kamiblue/client/util/threads/ThreadSafety.kt
A much better fix for b9553fc
Minecraft's scheduled task blocks the thread when adding task or waiting for result. Which is wasting threads or leading to thread deadlock.
=> [new] Implemented non blocking main thread execution with deferred callback

src/main/kotlin/org/kamiblue/client/gui/hudgui/HudElement.kt
Closes #1910
adds a default option to hud elements.
=> [feature] Add default button to hud elements

src/main/kotlin/org/kamiblue/client/module/modules/render/ItemModel.kt
One line change to allow people to find this module by searching for SmallShield like it's named in other clients.
=> [enhancement] Add SmallShield alias to ItemModel for discoverability

src/main/kotlin/org/kamiblue/client/module/modules/misc/StashLogger.kt, src/main/kotlin/org/kamiblue/client/module/modules/misc/TeleportLogger.kt
Makes it more understandable for the end user and describes what it actually does.
I have seen other people be confused and been confused myself, it doesn't save it to a file it saves it to your waypoints.
=> [enhancement] rename save to file to save to waypoints

src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/FPS.kt, src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/TPS.kt, src/main/kotlin/org/kamiblue/client/module/modules/client/Capes.kt, src/main/kotlin/org/kamiblue/client/util/CircularArray.kt, src/main/kotlin/org/kamiblue/client/util/TpsCalculator.kt
Introduce CircularArray to provide the functionality that was manually written in a few places
Move to using nanoTime to avoid an issue where NTP sync would cause TPS shift.
I kept the HUD TPS buffer around since it allows for the HUD to appear to have a fun moving number for the A E S T H E T I C.
=> [enhancement] Refactor TPS/FPS Calculation

src/main/kotlin/org/kamiblue/client/event/ForgeEventProcessor.kt, src/main/kotlin/org/kamiblue/client/gui/GuiManager.kt, src/main/kotlin/org/kamiblue/client/gui/hudgui/HudElement.kt
Adds key binds to gui elements.
=> [enhancement] Added binds to HUD elements.

src/main/kotlin/org/kamiblue/client/module/modules/misc/AutoObsidian.kt
Hotfix for patched mining sequence.
=> [fix] Hotfix mining packet sequence

src/main/java/org/kamiblue/client/mixin/client/render/MixinRenderGlobal.java, src/main/java/org/kamiblue/client/mixin/client/render/MixinRenderPlayer.java, src/main/java/org/kamiblue/client/mixin/client/render/MixinViewFrustum.java, src/main/resources/mixins.kami.json
Replaced redirect inject with inject or modify variable for compatibility. Should fix #1886, need test from some with Pyro.
Works in both vanilla/Optifine and both out or dev / in dev.
Also #1759 didn't fully fixed the invisible chunks bug in Optifine. Need to find a way to fix it later.
=> [fix] Freecam mixin compatibility

src/main/kotlin/org/kamiblue/client/module/modules/misc/AutoObsidian.kt
IDE did not detect that serverBrand can be null. This should fix any crash caused by this.
=> [fix] player.serverBrand must not be null

src/main/kotlin/org/kamiblue/client/module/modules/player/AutoEat.kt
if health goes below x > eat gap
if hunger goes below x > eat food
if on fire and have an enchanted gap -> eat it
closes #1853
=> [enhancement] AutoEat food preference.

src/main/kotlin/org/kamiblue/client/command/commands/NBTCommand.kt, src/main/kotlin/org/kamiblue/client/module/modules/chat/ChatEncryption.kt
closes #2119
Copies to clipboard and pastes from clipboard.
=> impr: Copy NBT data to clipboard

src/main/kotlin/org/kamiblue/client/gui/rgui/component/StringButton.kt
Swap from right click to left click.
=> impr: Use left click to edit String settings

src/main/kotlin/org/kamiblue/client/gui/rgui/component/StringButton.kt
Add a blinking cursor when string settings are listening.
closes #2151
=> enh: add cursor to string settings.

src/main/kotlin/org/kamiblue/client/util/EntityUtils.kt, src/main/kotlin/org/kamiblue/client/util/graphics/font/TextComponent.kt
Adds the long waited font size option for HUD prints.
PS: When having different sizes in one line it does not align perfectly
=> impr: size option for TextComponents

src/main/java/org/kamiblue/client/mixin/client/render/MixinModelBoat.java, src/main/kotlin/org/kamiblue/client/module/modules/movement/BoatFly.kt, src/main/kotlin/org/kamiblue/client/module/modules/movement/EntitySpeed.kt, src/main/kotlin/org/kamiblue/client/util/EntityUtils.kt
Separates Boatfly from EntitySpeed
Because Boatfly shouldn't fall under EntitySpeed.
Closes #1552 
I Probably messed up some formatting and missed some of BoatFly in EntitySpeed and didn't clean up, so this is far from perfect. but both modules are functional, so we'll see!
=> impr: Separate BoatFly from EntitySpeed

src/main/kotlin/org/kamiblue/client/module/modules/render/EyeFinder.kt, src/main/kotlin/org/kamiblue/client/module/modules/render/WaypointRender.kt
convert to using proper colour settings in WaypointFinder and EyeFinder,
=> fix: Use proper color settings for WaypointFinder and EyeFinder

src/main/kotlin/org/kamiblue/client/gui/rgui/windows/ColorPicker.kt
Don't really know how to describe this, however the colour now changes as the user changes the colour, not after the user is done, however it allows people to still click cancel.
=> enh: Preview color value as it's being changed in ColorPicker

src/main/kotlin/org/kamiblue/client/command/commands/WaypointCommand.kt, src/main/kotlin/org/kamiblue/client/manager/managers/WaypointManager.kt
Adds the ability to pull waypoints from baritone into KAMI Blue.
closes #2148
=> impr: Add ability to sync waypoints from Baritone

src/main/kotlin/org/kamiblue/client/module/modules/render/WaypointRender.kt
=> enh: Show waypoints on radar

src/main/kotlin/org/kamiblue/client/module/modules/client/Baritone.kt
Adds an option to display baritone's path on the radar.
closes #2147
=> enh: Option to show Baritone path on Radar

src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/Queue2B2T.kt
Messy 3 AM Code, but it works
Adds a new HUD Element, showing the 2B2T Queue Status. This currently uses an experimental API, Planned to be ready for production use within the week.
Partially Satisfies #1101
Messy 3 AM Code, but it works. Definitely needs cleaned up.
=> new: 2B2T Queue HUD Element

src/main/java/org/kamiblue/client/mixin/client/world/MixinBlockLiquid.java, src/main/kotlin/org/kamiblue/client/module/modules/player/BlockInteraction.kt
=> enh: Add BlockOnly option to LiquidInteract

src/main/kotlin/org/kamiblue/client/gui/AbstractKamiGui.kt
fixes the bug mentioned in #2183
fixes #2183
=> fix: GUI scrolling bug

src/main/java/org/kamiblue/client/mixin/client/render/MixinModelBoat.java, src/main/kotlin/org/kamiblue/client/module/modules/movement/BoatFly.kt
Adds a scaling slider to increase/decrease the size of the boat while boatflying
0.5 Scaled boat
1.5 Scaled boat
The visual bug (**Fixed**)
=> enh: Boatfly scale modifier

src/main/java/org/kamiblue/client/mixin/client/world/MixinWorld.java, src/main/kotlin/org/kamiblue/client/module/modules/render/NoRender.kt
quick fix for skylight lag
It fixes skylight no render not working on the ban machines
=> enh: Add option to disable all server side light rendering in NoRender
