kami-blue/client

src/main/java/me/zeroeightsix/kami/KamiMod.java
src/main/java/me/zeroeightsix/kami/gui/kami/DisplayGuiScreen.java
src/main/java/me/zeroeightsix/kami/module/Module.java
src/main/java/me/zeroeightsix/kami/module/ModuleManager.java

custom module names aren't known as compile-time, so if a user renamed "Freecam" to "Spectator", or something similar, the lookup map would surely map "Spectator" to the "Freecam" module, but the code still asks ModuleManager for "Freecam" regardless.

ModuleManager fixes / improvements

---

src/main/java/me/zeroeightsix/kami/module/ModuleManager.java

* Created a `T getModuleT(Class<T>)` method so that no casting is needed after getting module.

[O] Optimize getModule return type

---

src/main/java/me/zeroeightsix/kami/gui/kami/RenderHelper.java
src/main/java/me/zeroeightsix/kami/module/modules/render/Search.java

Added a search module, highlights blocks in world based on their Minecraft map item colour.
`;set search add <BLOCKNAME>` adds a block to search, if player adds block air, it gets ignored. 
eg: `;set search add minecraft:log`
`;set search del <BLOCKNAME>` removes a block to search.
eg: `;set search del minecraft:log`
`;set search blocks [string]` lists or sets the entire list of blocks. 
eg: `;set search blocks` will return `minecraft:portal,minecraft:end_portal_frame,minecraft:bed,` unless the player has changed the block list.
`;set search blocks minecraft:log,minecraft:crafting_table` will overwrite the list with `minecraft:log,minecraft:crafting_table`.
NOTE: if player adds a none existant block it will show up in the search list but will be ignored.
EDIT: this resolves #495

Added Search module.

---

src/main/java/me/zeroeightsix/kami/mixin/client/MixinMinecraft.java

Previously, the mod was using `@Redirect` to run its `save()` method for saving the configuration upon a crash.  
However, this completely skips the normal crash report handler, which has two major drawbacks:
* When a crash is about to occur, the client freezes instead and never exits;
* If the crash is caused by a compatibility issue, the other mod developers may never see the crash report.
What this PR proposes is to `@Inject` before the call to `displayCrashReport` instead, letting the client exit as normal.
Same as zeroeightysix/KAMI#189

MixinMinecraft: Don't redirect the crash report handler, inject instead

---

src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt

This adds an off-by-default 'Log To File' setting to the VisualRange module.
This might not be useful to most people but for me this would go well with the StashFinder module when flying AFK and unexpectedly coming across players (who might be near their base for example).

Added a 'Log To File' to the VisualRange module.

---

src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatFilter.java
src/main/java/me/zeroeightsix/kami/module/modules/combat/AimBot.kt
src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoMend.kt
src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
src/main/java/me/zeroeightsix/kami/module/modules/player/PacketCancel.kt
src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.java
src/main/java/me/zeroeightsix/kami/module/modules/render/HungerOverlay.kt

When testing some other changes I noticed certain settings were not saved in my IntelliJ development build, where others worked fine. This is the result of certain Settings.<type>Builders not being built. This pull request hopefully adds the missing .build() calls to all settings lacking this call.

Added '.build()' calls to settings lacking this call.

---

src/main/java/me/zeroeightsix/kami/module/modules/player/NoFall.kt

This prevents the NoFall module in bucket mode from using a water bucket when the player is in creative mode or in the nether. 
Using the bucket in these situations served no purpose and could actually do more harm than good, as it could destroy torches/grass/decoration while building in creative mode, and would simply waste the bucket in the nether dimension.

NoFall in bucket mode won't use bucket in creative mode or the nether dimension.

---

src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt

This commit adds droppers and dispensers as additional options to the stashfinder module. These options are off by default, but could come in handy when looking for old stashes that predate these blocks being included in modern storageESP plugins.

Added the option to look for droppers and dispensers in stashfinder.

---

src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.java

The 'doLocale' setting in the 'InfoOverlay' settings is now hidden when selecting the H24 timeunit, as the setting does nothing in this mode.

Hide doLocale setting when in H24 timeunit mode.

---

src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatTimestamp.kt

This is the same change from my last pull request, but now fixed in the chatTimestamp module.

Implemented the same 'hidden doLocale' for the chatTimestamp module.

---

src/main/java/me/zeroeightsix/kami/module/modules/player/Fastuse.kt

When in spectator mode, setting fastuse to 'all' will result in the following error:
Java.lang.IllegalArgumentException: Invalid hand null
This pull request fixes this by not executing any fastuse code while in spectator mode.

Fixed an error being raised in 'all' fastuse mode while the player is a spectator.

---

src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt
src/main/java/me/zeroeightsix/kami/module/modules/player/PacketCancel.kt

Fixes being unable to rejoin if you left packet cancel set to all and enabled, adds an option to disable Aura on death.
See above 
No

Improved Aura and fixed a bug with Packet Cancel

---

src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.kt

This pull request:
- Removes a duplicate line from the code.
- Adds a 'both' option for logging spam messages to chat and file.
- Inverts the 'filterDMs' setting to now filter spam when turned on.
- Adds a 'filterServer' setting that will filter Server messages when turned on, and leave them be otherwise.
- Removes the > character from the SPECIAL_BEGINNINGS regex to make the greenText setting work on its own.

Some updates to the AntiSpam module.

---

src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatFilter.java
src/main/java/me/zeroeightsix/kami/module/modules/chat/LoginMessage.kt
src/main/java/me/zeroeightsix/kami/module/modules/chat/Spammer.java

https://github.com/kami-blue/client/issues/766
---
name: issue #766 
about: Fix for issue #766 
---

Fix Spammer doesn't support cyrillic symbols 

---

src/main/java/me/zeroeightsix/kami/module/modules/player/Fastuse.kt

This implements a 'chargeState' setting that allows the user to set the minimum chargeState required to shoot a bow, as requested in issue #799. The game hasn't used the described "1, 2, 3" state functionality anymore since version 1.9 however, so this instead gives the full range of minimum to max strength.
While working on this I noticed the 'all' mode ignored this entirely due to how the conditional was formatted, so I fixed that as well.

FastUse bow bugfix and feature implementation.

---

src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.java

This is a simple addition for showing the current biome in the info overlay that can be toggled with a setting (off by default).

Added a 'biome' setting to the info overlay.

---

src/main/java/me/zeroeightsix/kami/module/modules/render/Brightness.java

The fullbright module has a 'transition' setting, which gradually transitions from dark to light and light to dark when turning the module on or off.
When transition is off, a user would expect the brightness to transition instantly, but instead it does nothing, which is fixed by this pull request.

Fixed fullbright only working if transition is on.

---

src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraReplace.kt

This pull request does the following:
- elytraCount and chestplateCount are now based on items meeting the set threshold, not all items.
- Cleaned up some conditionals that will result in less checks and code execution overall.
-  Added a 'logToChat' function that tells you when you are running out of elytras, with an optional playSound setting and an adjustable logThreshold.
These new features come in handy on long journeys when you aren't paying much attention to your inventory or GUI.

Some ElytraReplace changes.

---

src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoTunnel.kt

So actually customsize #tunnel is kinda *censored* so I decided to make kami use default #tunnel command without any customizations etc
It is useful because as I said #tunnel is better than #tunnel 2 1 1000, you can test it yourself and see the big difference
Sorry for bad code im new in java/kotlin
:nojava: :nokotlin:

Fix customsize #tunnel if AutoTunnel settings are default

---

src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.kt

Anti-Zispanos makes it so that Anti-Spam ignores messages with Zispanos + (Adjective)
I hate having to see "Zispanos {thing}" all the time.

Added AntiZispanos

---

src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt

Please see #907 for more details.
I chose to have the setting called friends, have friends included if the option is true and default the option to true so as not to require change to existing configs, and to match the labeling/logic of Tracers.

Ignore friends option for VisualRange

---

src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
src/main/java/me/zeroeightsix/kami/module/modules/render/Search.java
src/main/java/me/zeroeightsix/kami/module/modules/render/StorageESP.kt
src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
src/main/java/me/zeroeightsix/kami/util/KamiTessellator.java

Option in StorageESP and search modules to have tracers point to blocks.
Easier to find blocks you're looking for.

Added option for tracers for StorageESP and Search #619

---

src/main/java/me/zeroeightsix/kami/module/modules/player/Fastbreak.kt

Click on a block once, it will mine automatically without even looking at it.
Closes #796. Also speed up digging.

Adding packet mode to fastbreak, issue #796

---

src/main/java/me/zeroeightsix/kami/module/modules/combat/Criticals.kt

A mode that makes you jump and delays attack packet and swing packet when you hit an entity. The packets will be sent when you start falling down.
Bypass critical patch on 2b2t.
The original mode will be named as packet mode.
Closes #810

Added delay mode to Criticals

---

src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt

1, Replace MathHelper functions with Kotlin functions.
2, Move look boost codes into a separated function.
3, Look boost will not be triggered if not moving forward.
4, Added space bar trigger option for look boost.
5. Improved auto boost.
6. Update server-side pitch in the beginning and the end of boosting.
1, Avoids exceeding the speed limit on some servers because of miscalculation, issue #942 
2, Easier to maintain the code.
3, Allows you look around freely without going into boosting status when not moving.
4, Allows you look up freely while flying, issue #938 
5, Make it works properly at all pitch and all direction.
6, Allows you to use auto boost without needing looking down manually, issue #938   …

Greatly improved ElytraFlight and added Space trigger

---

src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java
src/main/java/me/zeroeightsix/kami/module/modules/client/ActiveModules.java

This pull adds an option, ShowHidden, to the ActiveModules module that displays all enabled modules in the ActiveModules list.
Like most people, I try to keep my overlay clean by removing most of the modules I have enabled all the time from the ActiveModules list. But sometimes I can't remember if I have something enabled or not, and I have to search through the clickGUI to find out. The option ShowHidden displays all active modules to the ActiveModule list even if they have been toggled to not show on array. This makes it easy to see all of the active modules.
I'm very bad at naming things so if anything doesn't seem to have a good name I don't care if it's changed

Add ShowHidden option to ActiveModules

---

src/main/java/me/zeroeightsix/kami/module/modules/render/SelectionHighlight.kt

Checks if player eye position is in a block or not instead disabling it while Freecam is on
Remains functionality while Freecam on

Fixed SelectionHighlight issue with Freecam in a smarter way

---

src/main/java/me/zeroeightsix/kami/module/modules/render/Nametags.java

Adds item nametags with the current rendering implementation.
Resolves #921
Kinda/maybe/sorta starts a bit of #673
Cleans up a bit of 086's stream code and logic to make it a bit more readable/editable. Expands it a lot though, thanks java.
I'm not experienced enough with opengl so I can't do any of the fancy stuff like automatically checking for nametag overlaps with stacks of various different items. There is a lot of room for expansion here. Sorry its not Xiaro level code!

Added Items to Nametags

---

src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
src/main/java/me/zeroeightsix/kami/gui/kami/component/Potions.java
src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiPotionUi.java
src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiTheme.java
src/main/java/me/zeroeightsix/kami/util/PotionInfo.kt
src/main/java/me/zeroeightsix/kami/util/textUtils/RomanNumerals.kt

Adds an area where active potion effects are listed.
Changed a few minimum widths so that pins and expand/collapse buttons do not overlap text.
Resolves #707 
Makes the GUI a bit nicer to look at and interact with.
I was considering using the primary and secondary colors chosen by the player in `InfoOverlay` but I was unsure if the colors were intended to apply to all parts of the GUI or only that specific section. It would be useful if each label had a primary and secondary color that could be used freely. Maybe add it to the GUI todo list?

Added Potion Effects UI

---

src/main/java/me/zeroeightsix/kami/module/modules/render/ChunkFinder.java

1. Fixed ChunkFinder not drawing lines around the whole chunk
2. Removed unused imports
3. Use interpolated player pos for smoother drawing while moving up and down.

ChunkFinder bug fixes and small enhancement 

---

src/main/java/me/zeroeightsix/kami/module/modules/movement/EntitySpeed.kt

This pull should make so that boats abide by the Flight setting when using the EntitySpeed module. It should also make so that secondary passengers won't attempt to control boats since it is not possible.
Currently, people have no option to disable flight for boats which can cause them to be kicked or banned for flying when they would not be so otherwise.

Made EntitySpeed flight option works for boat, added primary passenger check

---

src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.kt
src/main/resources/assets/minecraft/shaders/post/esp_outline.json
src/main/resources/assets/minecraft/shaders/program/esp_outline.fsh
src/main/resources/assets/minecraft/shaders/program/esp_outline.json

1. Added shader esp with options of filled, outline, hiding model, blurred background.
1. Better and cooler esp
1. Too lazy to add Gaussian blur. I just use the minecraft one.
2. #1161 Tried to add that to StorageESP. Failed because the way of how minecraft renders tile entity. So just leave it open.
Example:

[feature] Shader ESP 

---

src/main/java/me/zeroeightsix/kami/mixin/client/MixinNetHandlerPlayClient.java
src/main/java/me/zeroeightsix/kami/mixin/client/MixinTileEntityEnchantmentTableRenderer.java
src/main/java/me/zeroeightsix/kami/module/modules/render/NoRender.kt
src/main/resources/mixins.kami.json

I changed the chunk event to be fired after the chunk parsing so you can modify the results.
I then modify the results of the parsed packet to have snowlayers where Enchantingtables would be.
This only changes blocks if the option was active while the chunkpacket came in !!!
I made an option for canceling the rendercall for the book on top of Enchantingtables.
In the future it would be good to make a custom block for possibly every tileentity with the correct hitbox and textures so you can render that when a tileentity would have been rendered.

[feature] Enchanting Table books option for NoRender

---

src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.kt
src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoReconnect.kt

The following changes were made to fix autoreconnect and antiAFK module bugs:
1. autoreconnect max delay increased to 100s for 2b2t (needs at least 30s max for queue)
2. autoreconnect count down instead of up for reconnect timer message
3. Reset timer when activating antiAFK module
4. Removed a condition from antiAFK module that was preventing baritone from cancelling its path when antiAFK was disabled

[fix] Fix Autoreconnect and AntiAfk bug

---

src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.kt

This PR is related to #1293.
This feature leaves to the user the possibility to eat bad food or not, when using the AutoEat module.
By default, the module does not eat bad food.
This includes :
- Rotten flesh
- Spider eye
- Poisonous potato
- Pufferfish
- Clown fish
Removed the chorus fruit as auto-eatable ressource as @l1ving stated in a answer #1293.

[feature] EatBadFood setting for the AutoEat module

---

src/main/java/me/zeroeightsix/kami/module/modules/movement/Flight.kt

Entering a singleplayer world with flight enabled causes this crash.
https://hastebin.com/tufariposu.log
Fixes minor niche crash.
Quick and dirty fix, please feel free to propose better solution.

[fix] Flight crash in singleplayer

---

src/main/java/me/zeroeightsix/kami/module/modules/movement/AutoWalk.kt

Baritone would activate regardless of which setting was applied. This bug fixes it (hopefully)
Restores some old code that was removed (accidentally?) in the rewrite
Makes AutoWalk forward and backward mode work properly.
EZ 1-line edit with no testing

Fixed AutoWalk bug

---

src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt

Adds an option to the Tracers module allowing the user to modify when the ranged color starts changing.
Separates ranged color change from the rendering range option of the tracers.
Should close #1578.

Color change range for Tracers

---

src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt

Very small PR.
Like title says this hides the option named "ColorChangeRange" in the Tracers module if the option named "RangedColor" is not selected, because there is no need for this option to appear if the user did not activate ranged color.
I don't know how or why I forgot to add that to #1589 but here it is.
None.

[enhancement] colorChangeRange should only appear if rangedColor is selected on the Tracers module

---

src/main/java/me/zeroeightsix/kami/mixin/client/MixinMinecraft.java

This pull will replace the `@Inject` into `Minecraft#displayGuiScreen` with a simpler `@ModifyVariable`. It also uses `this.currentScreen` instead of `Wrapper.getMinecraft().currentScreen`.
The current method for firing events is undesirable. It cancels the entire rest of the method, which makes compatibility with other mods difficult if those mods wish to inject partway through the method. It also copies a lot of code from the original method, which is unnecessary, since it is not modified. This new method will reduce the amount of code needed and improve compatibility.
Also, using the shadowed `this.currentScreen` is more concise than using `Wrapper.getMinecraft()` to basically get itself, and then getting `currentScreen`. …

[cleanup] Minecraft#displayGuiScreen Mixin

---

src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/RadarUI.kt
src/main/java/me/zeroeightsix/kami/module/modules/render/NewChunks.kt

This pull request adds the NewChunks (previously only directly rendered) to the radar. This can give a better overview over the surrounding area than rendering it in the world.
The following settings are added in NewChunks: 
- renderMode: lets you select to render new chunks in the world, radar or both
- radarScale: Scale of the radar is now configurable, to allow using it both for mobs and for new chunks (maybe this should be moved to a dedicated radar menu, when one is added)
- removeMode: Allows to switch how chunks are removed. Either chunk unload, Max number or never
- maxNum: When removeMode is maxnumber and this number is reached the chunks with the greatest distance to the player are deleted first
In the NewChunks module I noticed that chunks are added multiple time, so I changed …

Added NewChunks to the Radar and improved unloading of NewChunks

---

src/main/java/me/zeroeightsix/kami/util/BaritoneUtils.kt

Sometimes, we call unpause() even though the temporary process lost
control. We should still change the paused variable to false if it is
paused regardless.

Fix not unpausing even though control is lost

---

src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/Armor.kt

This adds a new setting, CountElytras, under the Armor HUD.
If you have an elytra in your chestplate slot, the armor count will display the number of elytras in your inventory rather than the number of diamond chestplates.
If you are flying, it may be helpful to see how many elytras you have left.

[enhancement] Add an option to count elytras in Armor HUD

---

src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt

Go to the correct screen after anti disconnect whilst in single player.
Closes #1859.

[fix] Returning to wrong screen after AntiDisconnect

---

src/main/java/me/zeroeightsix/kami/module/modules/player/ChestStealer.kt

Adds a setting, "OnlyShulkers" to the ChestStealer module. If enabled, it will only steal or store shulker boxes.
This feature is useful for moving items within a stash, for example.
None

[enhancement] Add an OnlyShulkers option to ChestStealer

---

src/main/java/me/zeroeightsix/kami/gui/rgui/component/SettingSlider.kt
src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.kt
src/main/java/me/zeroeightsix/kami/setting/settings/SettingRegister.kt
src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/DoubleSetting.kt
src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/FloatSetting.kt
src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/IntegerSetting.kt
src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/NumberSetting.kt

Currently, this does cause a bit of a UX problem where the number jumps around if ALT is released and then the mouse moves.
Another possibility would be to check for ALT when the drag starts and switch step values then.
A clear and concise description of what the pull is for.
Improves the lives of the users when the step value is too large and they want to fine tune some settings
Scott#6969 ran into this for the AntiAFK module, which is why AntiAFK has it first.

[enhancement] Holding "LMENU" aka Alt can now use a separate step value

---

src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt

I think this was supposed to be fixed in 45735cdd0eed9f8a892fe50515ad9313aee8b4fd
It may surprise some users when surround enables seemingly randomly.

[fix] Disable enableInHole by default in surround

---

src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoMend.kt

AutoMend will just YEET XP Bottles even when you are not near the ground.
Additionally, fix up the "shouldMend" when an Item has Mending. Most Anarchy servers always have mending, but we should check for it to avoid wasting bottles.
Additionally, additionally, throw down by sending a rotation packet downward right before we throw, we might want to take velocity into account to throw slightly ahead to give the bottle time to hit the ground.

[fix] AutoMend should only try to mend when near blocks

---

src/main/java/me/zeroeightsix/kami/mixin/client/player/MixinEntityPlayer.java

Possibly would happen on other instances, we will want to test this some before pushing to master/release.
EntityPlayer was sending PlayerTravelEvent, this caused the EventProfiler handler to concurrently modify the Minecraft.profiler instead of the MinecraftServer.profiler.
Additionally, this caused problems when trying to test anything using PlayerTravelEvent as it was getting more than what it should have.

[fix] F3 Debug Pie would crash on Single Player

---

build.gradle

This pull request is pretty straight forward, it replaces `http` urls in the build.gradle with `https`.
- Seems like a pretty smart idea to not use http anymore.
- I'm sure you've seen this link, but: https://medium.com/bugbountywriteup/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb
I made sure that the changes didn't break anything, ran and built the client with no problems.

Bumped a few urls to https

---

src/main/java/org/kamiblue/client/mixin/client/MixinMinecraft.java
src/main/kotlin/org/kamiblue/client/event/events/MouseClickEvent.kt
src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/CPS.kt
src/main/kotlin/org/kamiblue/client/module/modules/misc/NoteBot.kt

Add a CPS indicator to the HUD, also fix the description of notebot to reflect that it can now also do nbs.
closes #1604

[enhancement] Add CPS to the HUD

---

src/main/kotlin/org/kamiblue/client/module/modules/render/NewChunks.kt

This removes any references to the Chunk outside of Minecraft internally.
We only need the ChunkPos anyways and it's a smaller object in memory to keep around.

[enhancement] Use ChunkPos instead of Chunk in NewChunks

---

src/main/kotlin/org/kamiblue/client/module/modules/movement/Strafe.kt
src/main/kotlin/org/kamiblue/client/util/MovementUtils.kt

Only has "NCP/NCP Strict" modes that were lightly tested against NCP.
AAC can be added if there is an AAC server specific speed tweak we need for an anarchy server.
Custom allows tuning manually, but we need more options as other methods are used.
This also gets rid of the "start delay" people have reported and complained about as they state that Future and other clients do not have this problem.
Tested on tree.ac as well as 5b5t and my own testing anarchy server.
We do have some "rubber banding" but it's after a long period of time and appears to be lag compensation related potentially. Still not sure what is exactly happening there, but it only seems to happen once and an while after 1 minute sometimes 45 seconds which seems to long for speed/survivalfly checks.

[enhancement] Add in Speed modifiers into Strafe

---

src/main/kotlin/org/kamiblue/client/module/modules/combat/AutoOffhand.kt

This allows tuning AutoOffhand to switch faster if the servers allow for it.
The move packet delayed is also tied to this and now runs half a tick faster since I moved the TickTimer to TICK units.

[feature] AutoOffHand adjustable delay

---

src/main/kotlin/org/kamiblue/client/module/modules/misc/TeleportLogger.kt
src/main/kotlin/org/kamiblue/client/module/modules/player/Freecam.kt

I checked with #1759 and was not able to reproduce the issue after removing loadRenderers.
This problem is exaggerated when we call the loadRenderers with OptiFine added.
We do not need to reload the entire rendering pipeline every time we leave FreeCam.
If we still encounter the issue, I would much rather block unloading chunks from the graphics pipeline and check to make sure that works with OptiFine.
I believe some hints can be seen at RenderGlobal.stopChunkUpdates()
EDIT: Fixed wording since I was more talking about the specific usage on exit. The rest of the PR looks valid and fixed a few rendering problems.

[fix] Stutter when leaving Freecam

---

src/main/kotlin/org/kamiblue/client/module/modules/movement/Strafe.kt
src/main/kotlin/org/kamiblue/client/util/EntityUtils.kt
src/main/kotlin/org/kamiblue/client/util/MovementUtils.kt

We should add a Water Speed or generic speed module for water movement controls.
For now, remove it from strafe due to default NCP checks triggering on this easily.

[fix] Disable Strafe when in or above water

---

src/main/kotlin/org/kamiblue/client/command/commands/ModifiedCommand.kt
src/main/kotlin/org/kamiblue/client/gui/rgui/component/BindButton.kt
src/main/kotlin/org/kamiblue/client/gui/rgui/component/EnumSlider.kt
src/main/kotlin/org/kamiblue/client/gui/rgui/component/SettingButton.kt
src/main/kotlin/org/kamiblue/client/gui/rgui/component/SettingSlider.kt
src/main/kotlin/org/kamiblue/client/gui/rgui/component/Slider.kt
src/main/kotlin/org/kamiblue/client/gui/rgui/component/StringButton.kt
src/main/kotlin/org/kamiblue/client/module/modules/client/ClickGUI.kt
src/main/kotlin/org/kamiblue/client/setting/settings/AbstractSetting.kt
src/main/kotlin/org/kamiblue/client/util/text/MessageSendHelper.kt

Adds a modified setting command that allows for easier debugging and easy resetting of changes.
Just click to reset.

[enhancement] Add a modified setting command.

---

src/main/kotlin/org/kamiblue/client/module/modules/misc/MidClickFriends.kt

uh, how did this happen.
It was printing the wrong message, if it could find the uuid it said it can't, and if it can't is said it can!!!

[fix] wrong message being displayed when adding friends.

---

build.gradle

This is coming in Kotlin 1.5.0 and we should shake out the bugs the best we can.
I can make this a gradle.properties file change to make it easily changed with build scripts.
https://blog.jetbrains.com/kotlin/2021/02/the-jvm-backend-is-in-beta-let-s-make-it-stable-together/
inb4 xiaro blocks it

[enhancement] useIR for Kotlin compiling to use the beta backend.

---

src/main/kotlin/org/kamiblue/client/event/events/RenderRadarEvent.kt
src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/world/Radar.kt
src/main/kotlin/org/kamiblue/client/module/modules/render/NewChunks.kt

This pull adds back the Radar to the new gui.
In addition several options are added:
- Scale of the radar
- Toggles for players, passive, neutral, hostile and invisible entities
- Background, grid, new and distant chunk color
The border and labels use the primary and secondary color of the component.
Uses EntityUtils.getTargetList to reduce duplicate code.
The setting to enable rendering of new chunks is in the newchunk module, because having a rendermode enum there also allows to only render new chunks in the radar.

[feature] Add Radar including NewChunks

---

src/main/kotlin/org/kamiblue/client/command/commands/SetCommand.kt

Print the actual value of the setting instead of the value that is attempting to be set. This used to only go wrong when the requested value is out of the possible range.

fix: set command printing incorrect value

---

src/main/kotlin/org/kamiblue/client/module/modules/player/PacketLogger.kt

Adds an option to change internal capture timing. Its good when modules cancel events and you still wanna see the packets in the list

impr: capture timing setting

---

src/main/kotlin/org/kamiblue/client/module/modules/render/Breadcrumbs.kt

Similar to pull yesterday, use the proper colour settings.

fix: Use proper color settings for Breadcrumbs

---

src/main/kotlin/org/kamiblue/client/module/modules/misc/AntiAFK.kt

Allows the setting of a custom reply for AntiAFK autoreply.
Satisfies #2166
Quick and simple fix, I had to shorten the default message because the default GUI size caused the default message to go off the side of the GUI element.

impr: Custom AntiAFK AutoReply

---

src/main/kotlin/org/kamiblue/client/gui/rgui/windows/ColorPicker.kt

closes #2190
closes #2189 
fix color preview and make it so that alpha is shown.

bug: Fix color picker preview
